# Generated by Django 6.0.7 on 2026-08-01 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skillcategory_remove_userprofile_skills_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abstract',
            field=models.TextField(blank=True, default='', help_text='Executive abstract or technical implementation spec for freelancers'),
        ),
        migrations.AddField(
            model_name='project',
            name='attached_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='attached_file_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='code_quality_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='deadline_adherence_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='project_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proposal'),
        ),
        migrations.AlterField(
            model_name='review',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contract'),
        ),
        migrations.CreateModel(
            name='SprintTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('To Do', 'To Do (0%)'), ('In Progress', 'In Progress (30%)'), ('Under Review', 'Under Review (60%)'), ('Done', 'Done (100%)')], default='To Do', max_length=30)),
                ('budget', models.CharField(default='$2,500', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sprint_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='api.project')),
            ],
        ),
    ]
