# Generated by Django 6.0.7 on 2026-08-10 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('proposal', 'Proposal Event'), ('hired', 'Hiring Event'), ('milestone', 'Milestone Event'), ('payment', 'Payment & Escrow Event'), ('project', 'Project Event'), ('task', 'Task & Sprint Event'), ('message', 'Message Event'), ('general', 'General Notification')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('project_id', models.CharField(blank=True, default='', max_length=100)),
                ('project_name', models.CharField(blank=True, default='', max_length=200)),
                ('related_user_id', models.CharField(blank=True, default='', max_length=100)),
                ('related_user_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
