# Generated by Django 6.0.7 on 2026-08-15 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_savedfreelancer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='availability_status',
            field=models.CharField(blank=True, default='Available for Work', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='available_hours',
            field=models.CharField(blank=True, default='40 hrs/week', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='headline',
            field=models.CharField(blank=True, default='Senior React, PyTorch & Django Architect', max_length=200),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='location',
            field=models.CharField(blank=True, default='San Francisco, CA', max_length=150),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='resume_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='resume_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='resume_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='years_experience',
            field=models.CharField(blank=True, default='7+', max_length=20),
        ),
        migrations.CreateModel(
            name='FreelancerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(blank=True, default='', max_length=50)),
                ('expiry_date', models.CharField(blank=True, default='', max_length=50)),
                ('credential_id', models.CharField(blank=True, default='', max_length=100)),
                ('credential_url', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=200)),
                ('start_year', models.CharField(blank=True, default='', max_length=50)),
                ('end_year', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.CharField(blank=True, default='', max_length=50)),
                ('end_date', models.CharField(blank=True, default='', max_length=50)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills', models.CharField(blank=True, default='', max_length=200)),
                ('project_url', models.CharField(blank=True, default='', max_length=255)),
                ('github_url', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.TextField(blank=True, default='')),
                ('completion_info', models.CharField(blank=True, default='Completed', max_length=100)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
