# Generated by Django 6.0.7 on 2026-09-08 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_deactivated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agreed_amount',
            field=models.CharField(default='₹5,000', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='escrow_balance',
            field=models.CharField(default='₹5,000', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_rate',
            field=models.CharField(blank=True, default='₹75/hr', max_length=50),
        ),
        migrations.AlterField(
            model_name='contractmilestone',
            name='amount',
            field=models.CharField(default='₹2,500', max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='skills_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='years_experience',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(default='₹5,000', max_length=50),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='bid_amount',
            field=models.CharField(default='₹5,000', max_length=50),
        ),
        migrations.AlterField(
            model_name='sprinttask',
            name='budget',
            field=models.CharField(default='₹2,500', max_length=50),
        ),
    ]
