# Generated by Django 6.0.7 on 2026-09-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_contract_agreed_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='milestones_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Open for Bids'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
