# Generated by Django 6.0.7 on 2026-09-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_freelancerwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('proposal', 'Proposal Event'), ('hired', 'Hiring Event'), ('milestone', 'Milestone Event'), ('payment', 'Payment & Escrow Event'), ('project', 'Project Event'), ('task', 'Task & Sprint Event'), ('message', 'Message Event'), ('contract', 'Contract Event'), ('general', 'General Notification')], default='general', max_length=30),
        ),
    ]
