# Generated by Django 6.0.7 on 2026-09-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_status',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
