# Generated by Django 6.0.7 on 2026-09-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_project_approval_status_project_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='verification_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='verification_status',
            field=models.CharField(default='Pending Verification', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(default='Pending Verification', max_length=30),
        ),
    ]
