# Generated by Django 6.0.7 on 2026-09-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_freelancerprofile_verification_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinttask',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprinttask',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_tasks', to='api.contractmilestone'),
        ),
        migrations.AddField(
            model_name='sprinttask',
            name='milestone_number',
            field=models.IntegerField(default=1),
        ),
    ]
