# Generated by Django 6.0.7 on 2026-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sprinttask_is_locked_sprinttask_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='milestones_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
