# Generated by Django 6.0.3 on 2026-09-30 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_freelanceridentityverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='verification_status',
            field=models.CharField(default='Not Submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(default='Not Submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectDocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('document_file_url', models.TextField(blank=True, default='')),
                ('document_file_size', models.CharField(blank=True, default='', max_length=50)),
                ('document_type', models.CharField(choices=[('Project Requirement Spec', 'Project Requirement Spec'), ('Technical Architecture Abstract', 'Technical Architecture Abstract'), ('Design Specs & Wireframes', 'Design Specs & Wireframes'), ('Project Scope Document', 'Project Scope Document')], default='Project Requirement Spec', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_document_verifications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to='api.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
